{% set version = "1.24.1" %}

package:
  name: distributed
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/d/distributed/distributed-{{ version }}.tar.gz
  sha256: 4731a83d1c5bebf7aefdcb42abcb5be4a871d7a85eabae9afaa97ff938820c8f

build:
  number: 1000
  entry_points:
    - dask-scheduler=distributed.cli.dask_scheduler:go
    - dask-ssh=distributed.cli.dask_ssh:go
    - dask-worker=distributed.cli.dask_worker:go
    - dask-remote=distributed.cli.dask_remote:go
    - dask-submit=distributed.cli.dask_submit:go
    - dask-mpi=distributed.cli.dask_mpi:go
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - click >=6.6
    - cloudpickle >=0.2.2
    - cytoolz >=0.7.4
    - dask-core >=0.18.0
    - futures  # [py2k]
    - msgpack-python
    - psutil
    - pyyaml
    - singledispatch  # [py2k]
    - six
    - sortedcontainers
    - tblib
    - toolz >=0.7.4
    - tornado >=4.5.1
    - zict >=0.1.3

test:
  imports:
    - distributed
    - distributed.cli
    - distributed.comm
    - distributed.deploy
    - distributed.diagnostics
    - distributed.protocol
  commands:
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help

about:
  home: http://distributed.readthedocs.io/en/latest/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: 'Distributed computing with Dask'
  description: |
    Distributed is a lightweight library for distributed computing in Python.
    It extends both the concurrent.futures and dask APIs to moderate sized
    clusters.
  doc_url: http://distributed.readthedocs.org
  doc_source_url: https://github.com/dask/distributed/blob/master/docs/source/index.rst
  dev_url: https://github.com/dask/distributed

extra:
  recipe-maintainers:
    - mrocklin
    - pitrou
    - jcrist
    - martindurant
    - jakirkham
    - marcelotrevisani
