{% set version = "1.18.3" %}

package:
  name: distributed
  version: "{{ version }}"

source:
  fn: distributed-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/distributed/distributed-{{ version }}.tar.gz
  sha256: 214e0febae46bb728946dbb26a5513880a1290ac5ca748479f7c5f2fbe64145f

build:
  number: 0
  entry_points:
    - dask-scheduler=distributed.cli.dask_scheduler:go
    - dask-ssh=distributed.cli.dask_ssh:go
    - dask-worker=distributed.cli.dask_worker:go
    - dask-remote=distributed.cli.dask_remote:go
    - dask-submit=distributed.cli.dask_submit:go
    - dask-mpi=distributed.cli.dask_mpi:go
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - click >=6.6
    - cloudpickle >=0.2.2
    - dask-core >=0.15.2
    - msgpack-python
    - psutil
    - six
    - tblib
    - toolz >=0.7.4
    - tornado >=4.5.1
    - zict >=0.1.2
    - sortedcontainers
    - futures  # [py2k]

test:
  imports:
    - distributed
    - distributed.cli
    - distributed.diagnostics
    - distributed.http
  commands:
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help

about:
  home: http://distributed.readthedocs.io/en/latest/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Distributed computing with Dask'

extra:
  recipe-maintainers:
    - mrocklin
    - koverholt
    - pitrou
    - jcrist
    - martindurant
