{% set version = "2022.1.1" %}


package:
  name: distributed
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/distributed/distributed-{{ version }}.tar.gz
  sha256: c227b5dd2c784830917679487f049fb943c154f1993f187d5c52076aa78a72d0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask-scheduler = distributed.cli.dask_scheduler:go
    - dask-ssh = distributed.cli.dask_ssh:go
    - dask-worker = distributed.cli.dask_worker:go

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip

  run:
    - python
    - click >=6.6
    - cloudpickle >=1.5.0
    - cytoolz >=0.8.2
    - dask-core {{ version }}
    - jinja2
    - msgpack-python >=0.6.0
    - packaging >=20.0
    - psutil >=5.0
    - pyyaml
    - sortedcontainers !=2.0.0,!=2.0.1
    - tblib >=1.6.0
    - toolz >=0.8.2
    - tornado >=5  # [py<38]
    - tornado >=6.0.3  # [py>=38]
    - zict >=0.1.3
    - setuptools <60.0.0

  run_constrained:
    - openssl !=1.1.1e

test:
  imports:
    - distributed
    - distributed.cli
    - distributed.comm
    - distributed.deploy
    - distributed.diagnostics
    - distributed.protocol
  commands:
    - pip check
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help
  requires:
    - pip

about:
  home: https://distributed.dask.org
  summary: Distributed scheduler for Dask
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    Distributed is a lightweight library for distributed computing in Python.
    It extends both the concurrent.futures and dask APIs to moderate sized
    clusters.
  doc_url: https://distributed.dask.org
  doc_source_url: https://github.com/dask/distributed/blob/main/docs/source/index.rst
  dev_url: https://github.com/dask/distributed

extra:
  recipe-maintainers:
    - mrocklin
    - jcrist
    - martindurant
    - jakirkham
    - marcelotrevisani
    - ogrisel
    - tomaugspurger
    - jrbourbeau
