{% set version = "1.12.2" %}

package:
  name: distributed
  version: "{{ version }}"

source:
  fn: distributed-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/distributed/distributed-{{ version }}.tar.gz
  md5: f962b409810738b747d7278cc4b9dda3

build:
  number: 0
  entry_points:
    - dask-scheduler=distributed.cli.dask_scheduler:go
    - dask-ssh=distributed.cli.dask_ssh:go
    - dask-worker=distributed.cli.dask_worker:go
    - dask-remote=distributed.cli.dask_remote:go
    - dask-submit=distributed.cli.dask_submit:go
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - bokeh >=0.12.1
    - boto3
    - click
    - cloudpickle >=0.2.1
    - dask >=0.11.0
    - locket
    - msgpack-python
    - psutil
    - s3fs >=0.0.6
    - six
    - tblib
    - toolz >=0.7.4
    - tornado >=4.2

test:
  imports:
    - distributed
    - distributed.bokeh
    - distributed.bokeh.status
    - distributed.bokeh.tasks
    - distributed.cli
    - distributed.diagnostics
    - distributed.http
  commands:
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help

about:
  home: http://distributed.readthedocs.io/en/latest/
  license: BSD 3-Clause
  summary: 'Distributed computing'

extra:
  recipe-maintainers:
    - mrocklin
    - koverholt
