{% set version = "1.15.0" %}

package:
  name: distributed
  version: "{{ version }}"

source:
  fn: distributed-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/distributed/distributed-{{ version }}.tar.gz
  sha256: 0465683f84b308fce54e3169c9f1b1091e97c6436e49e8a6e06af8716c773dd5

build:
  number: 0
  entry_points:
    - dask-scheduler=distributed.cli.dask_scheduler:go
    - dask-ssh=distributed.cli.dask_ssh:go
    - dask-worker=distributed.cli.dask_worker:go
    - dask-remote=distributed.cli.dask_remote:go
    - dask-submit=distributed.cli.dask_submit:go
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - bokeh >=0.12.3
    - boto3
    - click >=6.6
    - cloudpickle >=0.2.2
    - dask >=0.13.0
    - locket
    # - msgpack-python
    - pandas >=0.19.0
    - psutil
    - s3fs >=0.0.8
    - six
    - tblib
    - toolz >=0.7.4
    - tornado >=4.2
    - zict >=0.1.1
    - sortedcontainers

test:
  imports:
    - distributed
    - distributed.bokeh
    - distributed.bokeh.status
    - distributed.bokeh.tasks
    - distributed.cli
    - distributed.diagnostics
    - distributed.http
  commands:
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help

about:
  home: http://distributed.readthedocs.io/en/latest/
  license: BSD 3-Clause
  summary: 'Distributed computing'

extra:
  recipe-maintainers:
    - mrocklin
    - koverholt
    - pitrou
