# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FopJZEQJtG5BLQ4deHu3vgTGFAtqfz4a5+dnfeD12pEoYmVEl/4Vvr7bhS86F9y2U30R0KCZEbWAHaDQcvTPyZC/v3HldjpPKxy2M3DdlW9hSHlfkcpCxJHRqddMxOZwLaWvO8B5uJh7ZlL99tTPeUZrePClHY12pqDOmkSLH1RlOMmip93+NXoIPShaSexDI/ooxQnkkXRaLNn+Et3Ck7bHB96SbbJcJZ/VQ41MeLr0g9oVe5rnlOW103yV4lgmD1ZuxJm3GG+pke+xwi8jsljC/Pi+hjLZKcZGhsTprm34e4w8Z3IoeO4dkO6bdcB0KNGA488US/Gr8AepCUIlpCezo0J7ygUmD9qFWOOQzp3TGpLzvK8cFyrnpnm968dME0WOjIwOB7dZW8v6vXK5TJ0EBWTMz+uvI/90AwG7ngghAkRdM3mBdg1ybqwrnm6uaYZCG5bb69LYlWbqST3S1mE/T6ENHNa4hSJvq7dEfgJu0iJqpfubDnfTRHDJUxXBcaMnkld0VE18BWQFpP2NGbN0iKJ5uR8cNYJxoa2eNSSVO0/2K+0ygeWLZyOzfYrQUcPdOu5zWX3JE3+szOOkjzgBr2jUXYDFEZIRzRliNaHdDYOtqhpdRRpL6xZClBzcJPlVdF5Ee+H9nh5uM3y59GBpWSHt1oSifNtpnXiP/Cw="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_python3.6 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_python3.7 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi